In [1]:
#import library
import pandas as pd
import numpy as np
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler

In [5]:
#import data
data=pd.read_csv("olympia2.csv")

In [4]:
data

m100m  m200m  m400m  m800m  m1500m  m5000m  m10000m  Marathon
0   10.23  20.37  46.18   1.77    3.68   13.33    27.65    129.57
1    9.93  20.06  44.38   1.74    3.53   12.93    27.53    127.51
2   10.15  20.45  45.80   1.77    3.58   13.26    27.72    132.22
3   10.14  20.19  45.02   1.73    3.57   12.83    26.87    127.20
4   10.27  20.30  45.26   1.79    3.70   14.64    30.49    146.37
5   10.00  19.89  44.29   1.70    3.57   13.48    28.13    126.05
6    9.84  20.17  44.72   1.75    3.53   13.23    27.60    130.09
7   10.10  20.15  45.92   1.76    3.65   13.39    28.09    132.19
8   10.17  20.42  45.25   1.77    3.61   13.42    28.17    129.18
9   10.29  20.85  45.84   1.80    3.72   13.49    27.88    131.17
10  10.97  22.46  51.40   1.94    4.24   16.70    35.38    171.26
11  10.32  20.96  46.42   1.87    3.84   13.75    28.81    133.23
12  10.24  20.61  45.77   1.75    3.58   13.42    27.80    131.57
13  10.29  20.52  45.89   1.69    3.52   13.42    27.91    129.43
14  10.16  20.65  44.90   1.81    3.73   14.31    30.43    146.00
15  10.21  20.47  45.49   1.74    3.61   13.27    27.52    131.15
16  10.02  20.16  44.64   1.72    3.48   12.98    27.38    126.36
17  10.06  20.23  44.33   1.73    3.53   12.91    27.36    128.47
18   9.87  19.94  44.36   1.70    3.49   13.01    27.30    127.13
19  10.11  19.85  45.57   1.75    3.61   13.48    28.12    132.04
20  10.32  21.09  48.44   1.82    3.74   13.98    29.34    132.53
21  10.08  20.11  45.43   1.76    3.59   13.45    28.03    132.10
22  10.33  20.73  45.48   1.76    3.63   13.50    28.81    132.00
23  10.20  20.93  46.37   1.83    3.77   14.21    29.65    139.18
24  10.35  20.54  45.58   1.75    3.56   13.07    27.78    129.15
25  10.20  20.89  46.59   1.80    3.70   13.66    28.72    134.21
26  10.01  19.72  45.26   1.73    3.35   13.09    27.28    127.29
27  10.00  20.03  44.78   1.77    3.62   13.22    27.58    126.16
28  10.28  20.43  44.18   1.70    3.44   12.66    26.46    124.55
29  10.34  20.41  45.37   1.74    3.64   13.84    28.51    127.20
30  10.60  21.23  46.95   1.82    3.77   13.90    28.45    129.26
31  10.41  20.77  47.90   1.76    3.67   13.64    28.77    134.03
32  10.30  20.92  46.41   1.79    3.76   14.11    29.50    149.27
33  10.13  20.06  44.69   1.80    3.83   14.15    29.84    143.07
34  10.21  20.40  44.31   1.78    3.63   13.13    27.14    127.19
35  10.64  21.52  48.63   1.80    3.80   14.19    29.62    139.57
36  10.19  20.19  45.68   1.73    3.55   13.22    27.44    128.31
37  10.11  20.42  46.09   1.74    3.54   13.21    27.70    128.59
38  10.08  20.17  46.11   1.71    3.62   13.11    27.54    130.17
39  10.40  21.18  46.77   1.80    4.00   14.72    31.36    148.13
40  10.57  21.43  45.57   1.80    3.82   13.97    29.04    138.44
41  10.00  19.98  44.62   1.72    3.59   13.29    27.89    129.23
42   9.86  20.12  46.11   1.75    3.50   13.05    27.21    126.36
43  10.21  20.75  45.77   1.76    3.57   13.25    27.67    132.30
44  10.11  20.23  44.60   1.71    3.54   13.20    27.90    129.16
45  10.78  21.86  49.98   1.94    4.01   16.28    34.71    161.50
46  10.37  21.14  47.60   1.84    3.86   14.96    31.32    144.22
47  10.17  20.59  44.96   1.73    3.48   13.04    27.24    127.23
48  10.18  20.43  45.54   1.76    3.61   13.29    27.93    130.38
49  10.16  20.41  44.99   1.71    3.53   13.13    27.90    129.56
50  10.36  20.81  46.72   1.79    3.77   13.91    29.20    134.35
51  10.23  20.69  46.05   1.81    3.77   14.25    29.67    139.33
52  10.38  21.04  46.63   1.78    3.59   13.45    28.33    130.25
53   9.78  19.32  43.18   1.71    3.46   12.97    27.23    125.38

In [8]:
#mengubah data menjadi array X
x=np.array(data)

In [9]:
x

array([[ 10.23,  20.37,  46.18,   1.77,   3.68,  13.33,  27.65, 129.57],
       [  9.93,  20.06,  44.38,   1.74,   3.53,  12.93,  27.53, 127.51],
       [ 10.15,  20.45,  45.8 ,   1.77,   3.58,  13.26,  27.72, 132.22],
       [ 10.14,  20.19,  45.02,   1.73,   3.57,  12.83,  26.87, 127.2 ],
       [ 10.27,  20.3 ,  45.26,   1.79,   3.7 ,  14.64,  30.49, 146.37],
       [ 10.  ,  19.89,  44.29,   1.7 ,   3.57,  13.48,  28.13, 126.05],
       [  9.84,  20.17,  44.72,   1.75,   3.53,  13.23,  27.6 , 130.09],
       [ 10.1 ,  20.15,  45.92,   1.76,   3.65,  13.39,  28.09, 132.19],
       [ 10.17,  20.42,  45.25,   1.77,   3.61,  13.42,  28.17, 129.18],
       [ 10.29,  20.85,  45.84,   1.8 ,   3.72,  13.49,  27.88, 131.17],
       [ 10.97,  22.46,  51.4 ,   1.94,   4.24,  16.7 ,  35.38, 171.26],
       [ 10.32,  20.96,  46.42,   1.87,   3.84,  13.75,  28.81, 133.23],
       [ 10.24,  20.61,  45.77,   1.75,   3.58,  13.42,  27.8 , 131.57],
       [ 10.29,  20.52,  45.89,   1.69,   3.52,  13

In [10]:
# Create a scaler object 
sc = StandardScaler() 
# Fit the scaler to the features and transform 
X_std = sc.fit_transform(X)
X_std

array([[ 5.99715854e-02, -3.15545948e-01,  2.46203301e-01,
         3.56370950e-02,  1.95633310e-01, -3.81543587e-01,
        -5.32110380e-01, -4.40716219e-01],
       [-1.30839417e+00, -8.85982142e-01, -1.01664424e+00,
        -5.41683844e-01, -7.70604379e-01, -9.12215931e-01,
        -6.04245846e-01, -6.72997429e-01],
       [-3.04925948e-01, -1.68336607e-01, -2.03978460e-02,
         3.56370950e-02, -4.48525150e-01, -4.74411247e-01,
        -4.90031359e-01, -1.41907866e-01],
       [-3.50538140e-01, -6.46766964e-01, -5.67631779e-01,
        -7.34124157e-01, -5.12940996e-01, -1.04488402e+00,
        -1.00099091e+00, -7.07952368e-01],
       [ 2.42420352e-01, -4.44354120e-01, -3.99252107e-01,
         4.20517721e-01,  3.24465002e-01,  1.35640834e+00,
         1.17509564e+00,  1.45361598e+00],
       [-9.89108823e-01, -1.19880199e+00, -1.07978661e+00,
        -1.31144510e+00, -5.12940996e-01, -1.82541459e-01,
        -2.43568517e-01, -8.37623917e-01],
       [-1.71890389e+00, -6.835692

In [11]:
#Calculating Covariance Matrix
cov_matrix=np.cov(X_std.T)
cov_matrix

array([[1.01886792, 0.93201496, 0.81928668, 0.7253716 , 0.77862973,
        0.75384027, 0.72827874, 0.6892512 ],
       [0.93201496, 1.01886792, 0.86085768, 0.81195233, 0.82134862,
        0.77566696, 0.76206424, 0.73472165],
       [0.81928668, 0.86085768, 1.01886792, 0.78223463, 0.77108473,
        0.79440412, 0.78019619, 0.72612917],
       [0.7253716 , 0.81195233, 0.78223463, 1.01886792, 0.9017958 ,
        0.87693542, 0.85901505, 0.82219147],
       [0.77862973, 0.82134862, 0.77108473, 0.9017958 , 1.01886792,
        0.92145278, 0.90779536, 0.88316795],
       [0.75384027, 0.77566696, 0.79440412, 0.87693542, 0.92145278,
        1.01886792, 1.00687825, 0.96196066],
       [0.72827874, 0.76206424, 0.78019619, 0.85901505, 0.90779536,
        1.00687825, 1.01886792, 0.97216608],
       [0.6892512 , 0.73472165, 0.72612917, 0.82219147, 0.88316795,
        0.96196066, 0.97216608, 1.01886792]])

In [14]:
eigen_val,eigen_vec=np.linalg.eig(cov_matrix)
print("Eigenvalue :\n",eigen_val,"\n")
print("Eigenvector :\n",eigen_vec,"\n")

Eigenvalue :
 [6.81666042 0.64702852 0.23259238 0.21722131 0.00995385 0.04884462
 0.08109363 0.09754868] 

Eigenvector :
 [[ 0.33300212 -0.52825595  0.26028215 -0.4374155  -0.07051711  0.30981004
   0.49526977  0.0687681 ]
 [ 0.34738076 -0.4656522  -0.06559782 -0.20257282  0.06723888 -0.42439384
  -0.54943222 -0.36145381]
 [ 0.3389998  -0.34642725  0.14029178  0.82474226 -0.00554362  0.12819814
  -0.05347599  0.21415076]
 [ 0.35309272  0.09049139 -0.77422861  0.10935264 -0.04527851  0.18657537
   0.29035578 -0.36685406]
 [ 0.36401076  0.13771398 -0.32132227 -0.25783589 -0.02956603  0.00731066
  -0.27333146  0.77663762]
 [ 0.36984365  0.29858198  0.19400085  0.02236503  0.70485448 -0.37046597
   0.31913442  0.00403649]
 [ 0.36606144  0.33834764  0.25642653  0.03657855 -0.69741213 -0.40232252
   0.17501382 -0.07450111]
 [ 0.35433278  0.39155803  0.31968657 -0.08459679  0.06593726  0.61114694
  -0.39809449 -0.27467606]] 



In [17]:
var_explained=[]
for i in eigen_val:var_explained.append((i/sum(eigen_val))*100)
var_explained

[83.63032458651026,
 7.938081330932967,
 2.8535639089216134,
 2.664983661035264,
 0.12211893681118989,
 0.599251112537912,
 0.994898689592519,
 1.1967777736582907]

In [18]:
cumulative_var_explained=np.cumsum(var_explained)
cumulative_var_explained

array([ 83.63032459,  91.56840592,  94.42196983,  97.08695349,
        97.20907242,  97.80832354,  98.80322223, 100.        ])

In [19]:
# Create a pca object with the 2 components as a parameter 
pca = decomposition.PCA(n_components=2)

In [20]:
# Fit the PCA and transform the data 
X_std_pca = pca.fit_transform(X_std)
X_std_pca

array([[-0.41444199, -0.40639722],
       [-2.35691972,  0.56044515],
       [-0.72273972, -0.17502847],
       [-1.98347997, -0.3819565 ],
       [ 1.50449054,  1.67166781],
       [-2.21511175,  0.80058849],
       [-2.00880875,  0.864808  ],
       [-0.72171704,  0.34344526],
       [-0.71593485, -0.01653824],
       [ 0.39333761, -0.61109287],
       [10.77544773,  0.29167169],
       [ 1.81870964, -0.30715128],
       [-0.556657  , -0.50556374],
       [-1.11938144, -0.80790869],
       [ 1.49185594,  1.62649104],
       [-0.90790835, -0.37097882],
       [-2.40201962,  0.0540537 ],
       [-2.13950291,  0.09617056],
       [-2.92164687,  0.67569002],
       [-1.09851037,  0.64370521],
       [ 2.00952215, -0.9172787 ],
       [-1.02225086,  0.4993669 ],
       [ 0.05165114, -0.43688849],
       [ 1.81771311,  0.5038567 ],
       [-0.79923074, -0.93174781],
       [ 0.80340147, -0.25613135],
       [-2.71875786,  0.27086216],
       [-1.66040126,  0.5177898 ],
       [-2.60538758,

In [21]:
# Create a pca object with the 2 components as a parameter 
projection_matrix=(eigen_vec.T[:][:2]).T
projection_matrix

array([[ 0.33300212, -0.52825595],
       [ 0.34738076, -0.4656522 ],
       [ 0.3389998 , -0.34642725],
       [ 0.35309272,  0.09049139],
       [ 0.36401076,  0.13771398],
       [ 0.36984365,  0.29858198],
       [ 0.36606144,  0.33834764],
       [ 0.35433278,  0.39155803]])

In [22]:
# Getting the new feature data
X_pca=X_std.dot(projection_matrix)
X_pca

array([[-0.41444199, -0.40639722],
       [-2.35691972,  0.56044515],
       [-0.72273972, -0.17502847],
       [-1.98347997, -0.3819565 ],
       [ 1.50449054,  1.67166781],
       [-2.21511175,  0.80058849],
       [-2.00880875,  0.864808  ],
       [-0.72171704,  0.34344526],
       [-0.71593485, -0.01653824],
       [ 0.39333761, -0.61109287],
       [10.77544773,  0.29167169],
       [ 1.81870964, -0.30715128],
       [-0.556657  , -0.50556374],
       [-1.11938144, -0.80790869],
       [ 1.49185594,  1.62649104],
       [-0.90790835, -0.37097882],
       [-2.40201962,  0.0540537 ],
       [-2.13950291,  0.09617056],
       [-2.92164687,  0.67569002],
       [-1.09851037,  0.64370521],
       [ 2.00952215, -0.9172787 ],
       [-1.02225086,  0.4993669 ],
       [ 0.05165114, -0.43688849],
       [ 1.81771311,  0.5038567 ],
       [-0.79923074, -0.93174781],
       [ 0.80340147, -0.25613135],
       [-2.71875786,  0.27086216],
       [-1.66040126,  0.5177898 ],
       [-2.60538758,